In [4]:
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
random.seed(0)
%matplotlib inline

In [5]:
def load_data_from_file(fileName = 'advertising.csv'):
    data = np.genfromtxt(fileName, dtype=None, delimiter=',', skip_header=1)
    features_X = data[:, :3]
    sales_Y = data[:, 3]
    return features_X, sales_Y

In [8]:
features_X, sales_Y = load_data_from_file()
print(features_X [:5 ,:])
print(sales_Y.shape)

[[230.1  37.8  69.2]
 [ 44.5  39.3  45.1]
 [ 17.2  45.9  69.3]
 [151.5  41.3  58.5]
 [180.8  10.8  58.4]]
(200,)


In [ ]:
def create_individual(n=4, bound =10):
    individual = []
    for _ in range(n+1):
        
    return individual